on: push
name: on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: build
      run: dotnet build
    - name: setup-gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
    - name: pack
      shell: pwsh
      run: ./build.ps1
    - name: upload
      run: |
        gsutil cp -a public-read Libplanet.Explorer.Executable/bin/Release/libplanet-explorer.*.zip
        "gs://$BUCKET/${{ github.sha }}/"
      env:
        BUCKET: libplanet-explorer
    - name: share
      uses: shawnbot/action-status@v0.1.1
      env:
        BUCKET: libplanet-explorer
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        entrypoint: /bin/sh
        args: -c "for f in Libplanet.Explorer.Executable/bin/Release/libplanet-explorer.*.zip;
          do b=`basename $f`; /action-status/cli.js --context=bin/`echo $b | cut -d.
          -f2` --description=$b --url=https://storage.googleapis.com/$BUCKET/${{ github.sha
          }}/$b --state=success; done"
